### ISSUE TITLE
support for PostgeSQL 10.0+

### ISSUE THREAD

**Issue by nri-pl** [zalando/pg_view#100]
```
Traceback (most recent call last):
  File "/usr/bin/pg_view", line 11, in <module>
    load_entry_point('pg-view==1.4.1', 'console_scripts', 'pg_view')()
  File "/usr/lib/python3.6/site-packages/pg_view.py", line 3474, in main
    postmasters = get_postmasters_directories()
  File "/usr/lib/python3.6/site-packages/pg_view.py", line 3038, in get_postmasters_directories
    postmasters[pg_dir] = [pid, version, dbname]
UnboundLocalError: local variable 'version' referenced before assignment
```

# cat /proc/<PG PID>/cwd/PG_VERSION
10

```
fp = open(PG_VERSION_FILENAME, 'rU')
  val = fp.read().strip()
  print(val)                  
  if val is not None and len(val) >= 3:
      version = float(val)
```

I do not understand why "len(val) >= 3"
"len(val) >= 1" should be enought.

> Unable to read free space information for the pg_xlog and data directories for the directory             /pg: [Errno 2] No such file or directory: '/pg/pg_xlog/'
> ERROR: 2018-05-24 23:25:55,870 Unable to read free space information for the pg_xlog and data directories for the directory             /pg: [Errno 2] No such file or directory: '/pg/pg_xlog/'
> Process DetachedDiskStatCollector-1:
> Traceback (most recent call last):
> File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/usr/lib/python3.6/site-packages/pg_view.py", line 3560, in run
> df_data = self.get_df_data(wd)
> File "/usr/lib/python3.6/site-packages/pg_view.py", line 3615, in get_df_data
> xlog_dev = self.get_mounted_device(self.get_mount_point(work_directory + '/pg_xlog/'))
> File "/usr/lib/python3.6/site-packages/pg_view.py", line 3679, in get_mount_point
> parent_device = path_device = os.stat(pathname).st_dev
> FileNotFoundError: [Errno 2] No such file or directory: '/pg/pg_xlog'
>

**Comment by hjacobs** [comment]
@nri-pl thanks for reporting!

**Comment by alexeyklyukin** [comment]
>File "/usr/lib/python3.6/site-packages/pg_view.py", line 3474, in main

This looks like an old (one single file) version of pg_view. We moved one for more than a year.

> I do not understand why "len(val) >= 3"
> "len(val) >= 1" should be enought.

It's a valid point. That has been fixed at https://github.com/zalando/pg_view/pull/89
Feel free to give it a spin

**Comment by mohag** [comment]
Is there a release (or installation instructions) of the newer version? (pip seems to install 1.4.1, which has this issue)
