### ISSUE TITLE
Error running pg_view against PG 11.1

### ISSUE THREAD

**Issue by MichaelDBA** [zalando/pg_view#101]
Perhaps it is not supported yet, but this is the error I get when running pg_view --verbose: 
```

Traceback (most recent call last):
  File "/bin/pg_view", line 3718, in <module>
    main()
  File "/bin/pg_view", line 3470, in main
    postmasters = get_postmasters_directories()
  File "/bin/pg_view", line 3034, in get_postmasters_directories
    postmasters[pg_dir] = [pid, version, dbname]
UnboundLocalError: local variable 'version' referenced before assignment
```

**Comment by MichaelDBA** [comment]
Can I get a status update?

**Comment by CyberDem0n** [comment]
How did you installed it?
Master branch is working fine with PG 11

**Comment by MichaelDBA** [comment]
It is working now, but still a problem trying to specify a configuration file instead of command line parameters

**Comment by pmpetit** [comment]
Hello,
i have the same pb with pgsql 11.1
postgres-0:~$ pg_view
Traceback (most recent call last):
  File "/usr/bin/pg_view", line 11, in <module>
    load_entry_point('pg-view==1.4.1', 'console_scripts', 'pg_view')()
  File "/usr/lib/python2.7/site-packages/pg_view.py", line 3470, in main
    postmasters = get_postmasters_directories()
  File "/usr/lib/python2.7/site-packages/pg_view.py", line 3034, in get_postmasters_directories
    postmasters[pg_dir] = [pid, version, dbname]
UnboundLocalError: local variable 'version' referenced before assignment
postgres-0:~$ 

installed with "pip install pg-view"
