### ISSUE TITLE
Problem with version number

### ISSUE THREAD

**Issue by Vampouille** [zalando/pg_view#88]
```
Traceback (most recent call last):
  File "pg_view.py", line 6, in <module>
    main()
  File "/pg_view/pg_view/__init__.py", line 211, in main
    if not establish_user_defined_connection(instance, conn, clusters):
  File "/pg_view/pg_view/models/db_client.py", line 113, in establish_user_defined_connection
    dbver = dbversion_as_float(pgcon)
  File "/pg_view/pg_view/utils.py", line 102, in dbversion_as_float
    return float('{0}.{1}'.format(version_num / 100, version_num % 100))
ValueError: could not convert string to float: '9.0507.5.07000000000005'
```

**Comment by alexeyklyukin** [comment]
The issue is related to running pg_view under python3. #89 should fix it, you can check if it solves the issue on your system.

**Comment by elthariel** [comment]
I've just tried running using the suggested branch, and the result is the same

**Comment by vinnix** [comment]
I'm not used to run merges. I've tried #89 pull request this way:
```
git merge origin/bugfix/version_number
```
... and I the following message:
```
Auto-merging pg_view/__init__.py
Auto-merging pg_view/collectors/partition_collector.py
Auto-merging pg_view/collectors/pg_collector.py
Auto-merging pg_view/models/db_client.py
CONFLICT (content): Merge conflict in pg_view/models/db_client.py
Automatic merge failed; fix conflicts and then commit the result.
```

I fixed the file `db_client.py` around the line 232:
```
  File "/home/vinnix/Sources/Github/pg_view/pg_view/models/db_client.py", line 232
    <<<<<<< HEAD
```
to look like:
```
        PG_VERSION_FILENAME = '{0}/PG_VERSION'.format(link_filename)
        if not os.access(PG_VERSION_FILENAME, os.R_OK):
            logger.warning(
                'PostgreSQL candidate directory {0} is missing PG_VERSION file, have to skip it'.format(pg_dir))
            continue
        try:
            fp = open(PG_VERSION_FILENAME, 'rU')
            val = fp.read().strip()
            version = postgres_major_version_to_int(val)
        except os.error as e:
            logger.error(                                                                                                                                                                                                                     
                'unable to read version number from PG_VERSION directory {0}, have to skip it'.format(pg_dir))
            continue
        except ValueError:
            logger.error('PG_VERSION doesn\'t contain a valid version number: {0}'.format(val))
            continue
```
