### ISSUE TITLE
pg_is_in_recovery() does not exist

### ISSUE THREAD

**Issue by dutran123** [zalando/pg_view#97]
I am using Postgres 8.4 and get this error when running pg_view:

Traceback (most recent call last):
  File "./pg_view.py", line 3517, in main
    pg = PgstatCollector(cl['pgcon'], cl['reconnect'], cl['pid'], cl['name'], cl['ver'], options.pid)
  File "./pg_view.py", line 922, in __init__
    self.recovery_status = self._get_recovery_status()
  File "./pg_view.py", line 1314, in _get_recovery_status
    cur.execute("select case when pg_is_in_recovery() then 'standby' else 'master' end as role")
  File "/usr/lib64/python2.6/site-packages/psycopg2/extras.py", line 207, in execute
    return _cursor.execute(self, query, vars, async)
ProgrammingError: function pg_is_in_recovery() does not exist
LINE 1: select case when pg_is_in_recovery() then 'standby' else 'ma...
                         ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by alexeyklyukin** [comment]
Well, it doesn't exist, since anything before 8.4 does not support running queries on the nodes other than primary ones aka hot standby. 8.4 is EOL for 3,5 years (https://www.postgresql.org/support/versioning/), it makes more sense to spend time on upgrading ASAP from it rather than on supporting it.

If you still, for some wrong reason, insist on running 8.4, you can change your local pg_view, removing pg_is_in_recovery call altogether and replacing it with a constant 'master'.

**Comment by dutran123** [comment]
Thank you.  I commented out entire def _get_recovery_status(self):  function and any calls to it such as self._get_recovery_status().  I found a role = self._get_recovery_status and set that to role='master'.  Was that what you meant?  Doing that didn't help though.

Traceback (most recent call last):
  File "./pg_view.py", line 3525, in main
    loop(collectors, consumer, groups, output_method)
  File "./pg_view.py", line 2823, in loop
    curses.wrapper(do_loop, groups, output_method, collectors, consumer)
  File "/usr/lib64/python2.6/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./pg_view.py", line 2891, in do_loop
    process_single_collector(st)
  File "./pg_view.py", line 2921, in process_single_collector
    st.refresh()
  File "./pg_view.py", line 1199, in refresh
    stat_data = self._read_pg_stat_activity()
  File "./pg_view.py", line 1378, in _read_pg_stat_activity
    """)
  File "/usr/lib64/python2.6/site-packages/psycopg2/extras.py", line 207, in execute
    return _cursor.execute(self, query, vars, async)
ProgrammingError: syntax error at or near "ORDER"
LINE 9: ...                  string_agg(other.pid::TEXT, ',' ORDER BY o...

Thanks for your help in this. I can't upgrade postgresql to the latest version yet but hopefully soon.
